# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_elbo_cpp <- function(mu, sigma, omega, tau_b, mu_alpha, y_sq, y_dot_eta_bar, zeta, tau_alpha, tau_e, c_pi, d_pi) {
    .Call(`_spxlvb_compute_elbo_cpp`, mu, sigma, omega, tau_b, mu_alpha, y_sq, y_dot_eta_bar, zeta, tau_alpha, tau_e, c_pi, d_pi)
}

run_vb_updates_cpp <- function(X, Y, mu, omega, c_pi, d_pi, tau_e, update_order, mu_alpha, tau_alpha, tau_b, max_iter, tol, save_history = TRUE, convergence_method = 0L, update_pi = FALSE, elbo_offset = 0.0, disable_global_alpha = FALSE, track_coordinate_exploded_elbo = FALSE, track_all_criteria = FALSE, use_gamma_hyperprior_tau_alpha = FALSE, r_alpha = 0.0, d_alpha = 0.0, use_gamma_hyperprior_tau_b = FALSE, r_b = 0.0, d_b = 0.0, use_joint_optimization = FALSE, max_fp_iter = 10L) {
    .Call(`_spxlvb_run_vb_updates_cpp`, X, Y, mu, omega, c_pi, d_pi, tau_e, update_order, mu_alpha, tau_alpha, tau_b, max_iter, tol, save_history, convergence_method, update_pi, elbo_offset, disable_global_alpha, track_coordinate_exploded_elbo, track_all_criteria, use_gamma_hyperprior_tau_alpha, r_alpha, d_alpha, use_gamma_hyperprior_tau_b, r_b, d_b, use_joint_optimization, max_fp_iter)
}

