# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_elbo_cpp <- function(mu, sigma, omega, tau_b, mu_alpha, Y2, t_YW, t_W2, tau_alpha, tau_e, pi_fixed) {
    .Call(`_spxlvb_compute_elbo_cpp`, mu, sigma, omega, tau_b, mu_alpha, Y2, t_YW, t_W2, tau_alpha, tau_e, pi_fixed)
}

run_vb_updates_cpp <- function(X, Y, mu, omega, c_pi, d_pi, tau_e, update_order, mu_alpha, tau_alpha, tau_b, max_iter, tol, save_history = TRUE, convergence_method = 0L) {
    .Call(`_spxlvb_run_vb_updates_cpp`, X, Y, mu, omega, c_pi, d_pi, tau_e, update_order, mu_alpha, tau_alpha, tau_b, max_iter, tol, save_history, convergence_method)
}

